version: '3'

services:

  postgres:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: php_project
    ports:
      - 5432:5432

volumes:
  pgdata:
